apiVersion: apps/v1
kind: Deployment
metadata:
  name: seino
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: seino
      labels:
        app: seino
    spec:
      containers:
      - image: lseino/seino:v3
        name: nodejs
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080
