apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: seino
spec:
  replicas: 3
  selector:
    matchLabels:
      app: seino
  template:
    metadata:
      name: seino
      labels:
        app: seino
    spec:
      containers:
      - image: lseino/seino:v1
        name: nodejs
        resources:
          requests:
            cpu: 100m
