apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: seino
spec:
  replicas: 3
  template:
    metadata:
      name: seino
      labels:
        app: seino
    spec:
      containers:
      - image: lseino/seino:v1
        name: nodejs
        resources:
          requests:
            cpu: 100m
