apiVersion: v1
kind: ReplicationController
metadata:
  name: seino
spec:
  replicas: 3
  selector:
    app: seino
  template:
    metadata:
      labels:
        app: seino
    spec:
      containers:
      - name: seino
        image: lseino/seino
        ports:
        - containerPort: 8080
