apiVersion: v1
kind: Pod
metadata:
  name: seino-liveness
spec:
  containers:
  - image: lseino/seino-unhealthy
    name: seino
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15

