apiVersion: v1
kind: Pod
metadata:
  name: seino-xyz
  labels:
    app: seino
spec:
  containers:
  - image: lseino/seino
    name: seino
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      requests:
        memory: 300Mi
        cpu: .65
