apiVersion: v1
kind: Pod
metadata:
  name: seino-manual
  namespace: custom-namespace
spec:
  containers:
  - image: lseino/seino
    name: seino
    ports:
    - containerPort: 8080
      protocol: TCP
