apiVersion: v1
kind: Pod
metadata:
  name: seino-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: lseino/seino
    name: seino
    ports:
    - containerPort: 8080
      protocol: TCP
