apiVersion: v1
kind: ReplicationController
metadata:
  name: seino-v1
spec:
  replicas: 3
  template:
    metadata:
      name: seino
      labels:
        app: seino
    spec:
      containers:
      - image: lseino/seino:v1
        name: nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: seino
spec:
  type: LoadBalancer
  selector:
    app: seino
  ports:
  - port: 80
    targetPort: 8080
