apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: seino
spec:
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      name: seino
      labels:
        app: seino
    spec:
      containers:
      - image: lseino/seino:v3
        name: nodejs
